### ISSUE TITLE
Deployment Request Help

### ISSUE THREAD

**Issue by wozandy05** [narimiran/narimiran.github.io#2]
How did you deploy the blog website on github?

**Comment by narimiran** [comment]
> How did you deploy the blog website on github?

By using Github pages, available in settings.

**Comment by wozandy05** [comment]
But I just see 404 pages as if I need index.html in my repo.

**Comment by narimiran** [comment]
>  as if I need index.html in my repo

Well, I have it.

**Comment by wozandy05** [comment]
Oh, brother, you must have misunderstood me. You should have used the Rails framework to deploy your blog website. Otherwise, a static website cannot do these things, such as adding blog information and adding comments. How can I make a blog like you?

**Comment by narimiran** [comment]
I use Jekyll.
